apiVersion: v1
kind: Service
metadata:
  name: nextjs-demo
spec:
  type: ClusterIP
  selector:
    app: nextjs-demo # THIS MUST MATCH YOUR DEPLOYMENT LABELS
  ports:
    - protocol: TCP
      port: 3000 # Port accessible inside the cluster
      targetPort: 3000 # Port the Next.js container is listening on
