apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: postgres
  namespace: default

resources:
  - pv.yaml
  - pvc.yaml
  - secret.yaml
  - init-sql-configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: postgres
  managed-by: kustomize
