apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: postgres
  namespace: default

resources:
  - pv.yaml
  - pvc.yaml
  # - secret.yaml
  - init-sql-configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: postgres
  managed-by: kustomize

secretGenerator:
  - name: postgres-credentials
    literals:
      - POSTGRES_PASSWORD=your-secure-password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - DATABASE_URL=postgresql://postgres:your-secure-password@postgres:5432/postgres
# This is CRITICAL: it prevents Kustomize from adding a random
# hash to the name, so the Next.js app can find it easily.
generatorOptions:
  disableNameSuffixHash: true
